package com.example.peoplelistrememberappusingroomdatabase.data

import android.os.Parcelable
import androidx.room.Entity
import androidx.room.PrimaryKey
import kotlinx.android.parcel.Parcelize

@Parcelize
@Entity(tableName = "user_table")
data class User(
    @PrimaryKey(autoGenerate = true)
    val id: Int, // id will be a primary key which will be automatically generated by the room
    val firstName: String,
    val lastName: String,
    val age: Int
) : Parcelable